export const products = [
  {
    id: 1,
    name: "Expresso Tradicional",
    price: 9.9,
    tags: ["Tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    image: "/src/assets/cafes/expresso.png",
  },
  {
    id: 2,
    name: "Expresso Americano",
    price: 9.9,
    tags: ["Tradicional"],
    description: "Expresso diluído, menos intenso que o tradicional",
    image: "/src/assets/cafes/americano.png",
  },
  {
    id: 3,
    name: "Expresso Cremoso",
    price: 9.9,
    tags: ["Tradicional"],
    description: "Café expresso tradicional com espuma cremosa",
    image: "/src/assets/cafes/expressoCremoso.png",
  },
  {
    id: 4,
    name: "Expresso Gelado",
    price: 9.9,
    tags: ["Tradicional", "gelado"],
    description: "Bebida preparada com café expresso e cubos de gelo",
    image: "/src/assets/cafes/cafeGelado.png",
  },
  {
    id: 5,
    name: "Cafe com Leite",
    price: 9.9,
    tags: ["Tradicional", "com leite"],
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    image: "/src/assets/cafes/cafeComLeite.png",
  },
  {
    id: 6,
    name: "Latte",
    price: 9.9,
    tags: ["Tradicional", "com leite"],
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    image: "/src/assets/cafes/latte.png",
  },
  {
    id: 7,
    name: "Capuccino",
    price: 9.9,
    tags: ["Tradicional", "com leite"],
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    image: "/src/assets/cafes/capuccino.png",
  },
  {
    id: 8,
    name: "Macchiato",
    price: 9.9,
    tags: ["Tradicional", "com leite"],
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    image: "/src/assets/cafes/macchiato.png",
  },
  {
    id: 9,
    name: "Mocaccino",
    price: 9.9,
    tags: ["Tradicional", "com leite"],
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    image: "/src/assets/cafes/mochaccino.png",
  },
  {
    id: 10,
    name: "Chocolate Quente",
    price: 9.9,
    tags: ["Especial", "com leite"],
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    image: "/src/assets/cafes/chocolateQuente.png",
  },
  {
    id: 11,
    name: "Cubano",
    price: 9.9,
    tags: ["Especial", "alcoólico", "gelado"],
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    image: "/src/assets/cafes/cubano.png",
  },
  {
    id: 12,
    name: "Havaiano",
    price: 9.9,
    tags: ["Especial"],
    description: "Bebida adocicada preparada com café e leite de coco",
    image: "/src/assets/cafes/havaiano.png",
  },
  {
    id: 13,
    name: "Árabe",
    price: 9.9,
    tags: ["Especial"],
    description: "Bebida preparada com grãos de café árabe e especiarias",
    image: "/src/assets/cafes/arabe.png",
  },
  {
    id: 14,
    name: "Irlandes",
    price: 9.9,
    tags: ["Especial", "alcoólico"],
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    image: "/src/assets/cafes/irlandes.png",
  },
];
